---
# Install Oracle Java 7

# Installing via http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html
- name: Adding Java repository
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes state=present

- name: Auto accepting license for Java
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  
- name: Installing Oracle Java 7 and support libs
  apt: pkg={{ item }} state=latest install_recommends=yes
  with_items:
    - python-software-properties
    - oracle-java7-installer
    - oracle-java7-set-default
    - libjna-java
